#!/bin/bash
# Git setup instructions for MCP BacklinkContent Builder

echo "=== MCP BacklinkContent Builder - Git Setup ==="
echo ""
echo "1. Ladda ner och packa upp projektet:"
echo "   unzip mcp-blcwrtr-v0.1.0.zip"
echo "   cd mcp-blcwrtr"
echo ""
echo "2. Initiera Git-repo:"
echo "   git init"
echo "   git branch -M main"
echo ""
echo "3. Lägg till alla filer:"
echo "   git add ."
echo "   git commit -m 'feat: initial MCP backlink suite (v0.1.0)'"
echo ""
echo "4. Skapa GitHub-repo (om du inte redan har ett):"
echo "   # Gå till https://github.com/new"
echo "   # Skapa nytt repo: robwestz/mcp-blcwrtr"
echo "   # Välj Private eller Public"
echo "   # VIKTIGT: Skapa UTAN README, .gitignore eller License"
echo ""
echo "5. Koppla till GitHub och pusha:"
echo "   git remote add origin https://github.com/robwestz/mcp-blcwrtr.git"
echo "   git push -u origin main"
echo ""
echo "6. Verifiera på GitHub:"
echo "   # Gå till https://github.com/robwestz/mcp-blcwrtr"
echo "   # Alla filer ska nu vara uppladdade"
echo ""
echo "=== Alternativ: Använd befintligt repo ==="
echo ""
echo "Om du vill använda ditt befintliga blcwrtr-repo:"
echo "   git clone https://github.com/robwestz/blcwrtr.git"
echo "   cd blcwrtr"
echo "   # Kopiera in alla filer från mcp-blcwrtr/"
echo "   cp -r ../mcp-blcwrtr/* ."
echo "   git add ."
echo "   git commit -m 'feat: add MCP backlink suite'"
echo "   git push"
echo ""
echo "=== Snabbstart efter Git-setup ==="
echo ""
echo "1. Kopiera miljövariabler:"
echo "   cp .env.example .env"
echo ""
echo "2. Starta systemet:"
echo "   docker compose up -d"
echo ""
echo "3. Verifiera att allt körs:"
echo "   docker compose ps"
echo "   docker compose logs -f"
echo ""
echo "=== Support ==="
echo "Vid problem, skapa en issue på:"
echo "https://github.com/robwestz/mcp-blcwrtr/issues"
